version: 2

defaults: &defaults
  working_directory: /src
  docker:
    - image: golang:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Source
          command: ./build.sh
      - run:
          name: Check Formatting
          command: test -z $(go fmt ./...)
      - run:
          name: Vet Source
          command: go vet -all ./...
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
      - run:
          name: Check for Lint
          command: golangci-lint run ./...
      - run:
          name: Run Tests
          command: go test -cover -race -timeout 60s ./...

  get_source:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Populate Go Mod Cache
          command: |-
            if [ ! -d /go/pkg/mod ]; then
              go mod download
            fi
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Go Mod Verify
          command: go mod verify
      - persist_to_workspace:
          root: /
          paths:
            - go/pkg/mod
            - src

  build_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Build Source
          command: ./build.sh

  check_formatting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Check Formatting
          command: test -z $(go fmt ./...)

  vet_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Vet Source
          command: go vet -all ./...

  lint_source:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
      - run:
          name: Check for Lint
          command: golangci-lint run ./...

  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Run Tests
          command: go test -coverprofile cover.out -race -timeout 60s ./...
      - store_artifacts:
          path: cover.out
          destination: cover.out

workflows:
  version: 2

  build_and_test:
    jobs:
      - get_source
      - build_source:
          requires:
            - get_source
      - check_formatting:
          requires:
            - get_source
      - vet_source:
          requires:
            - get_source
      - lint_source:
          requires:
            - get_source
      - unit_test:
          requires:
            - get_source
