version: 2

defaults: &defaults
  working_directory: /src
  docker:
    - image: golang:1.12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Source
          command: ./build.sh
      - run:
          name: Check Formatting
          command: test -z $(go fmt ./...)
      - run:
          name: Vet Source
          command: go vet -all ./...
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
      - run:
          name: Check for Lint
          command: golangci-lint run ./...
      - run:
          name: Run Tests
          command: go test -cover -race -timeout 60s ./...

  lint_markdown:
    <<: *defaults
    docker:
      - image: node:11-slim
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint -i vendor .

  cache_go_mod:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Verify go.mod
          command: go list -mod=readonly ./... >/dev/null
      - run:
          name: Populate Go Mod Cache
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'

  build_source:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Build Source
          command: ./build.sh

  check_formatting:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Check Formatting
          command: test -z $(go fmt ./...)

  vet_source:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Vet Source
          command: go vet -all ./...

  lint_source:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
      - run:
          name: Check for Lint
          command: golangci-lint run ./...

  unit_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run:
          name: Run Tests
          command: go test -coverprofile cover.out -race -timeout 60s ./...
      - store_artifacts:
          path: cover.out
          destination: cover.out

workflows:
  version: 2

  build_and_test:
    jobs:
      - lint_markdown
      - cache_go_mod
      - build_source:
          requires:
            - cache_go_mod
      - check_formatting:
          requires:
            - cache_go_mod
      - vet_source:
          requires:
            - cache_go_mod
      - lint_source:
          requires:
            - cache_go_mod
      - unit_test:
          requires:
            - cache_go_mod
